branch-defaults:
  default:
    environment: airbnb-clone
    group_suffix: null
  master:
    environment: airbnb-clone
environment-defaults:
  airbnb-clone:
    branch: null
    repository: null
global:
  application_name: airbnb_last
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
